version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam
      POSTGRES_DB: iam_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "EPITA"
      LDAP_DOMAIN: "epita.fr"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - ldap

volumes:
  postgres_data:
